/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import form.Form_Deposit;
import form.Form_Pay;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Celsius
 */
public class Form_2Card extends javax.swing.JPanel {

    /**
     * Creates new form Form_2Card
     */
    public Form_2Card() {
        initComponents();

        // Add mouse listeners to the card components
        payCard.addMouseListener(new PayCardMouseListener());
        depositCard.addMouseListener(new DepositCardMouseListener());
    }

    private class PayCardMouseListener extends MouseAdapter {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Open the Form_Pay class design
            Form_Pay payForm = new Form_Pay();
            payForm.setVisible(true);
        }
    }
    
    private class DepositCardMouseListener extends MouseAdapter {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Open the Form_Deposit class design
            Form_Deposit depositForm = new Form_Deposit();
            depositForm.setVisible(true);
        }
    }
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payCard = new component.Card();
        depositCard = new component.Card();
        userPrompt = new javax.swing.JLabel();
        depositAction = new javax.swing.JLabel();
        payAction = new javax.swing.JLabel();

        payCard.setColor1(new java.awt.Color(51, 102, 255));
        payCard.setColor2(new java.awt.Color(153, 204, 255));

        depositCard.setColor1(new java.awt.Color(51, 102, 255));
        depositCard.setColor2(new java.awt.Color(153, 204, 255));

        userPrompt.setFont(new java.awt.Font("Barlow", 0, 24)); // NOI18N
        userPrompt.setText("Choose Apppropriate Action");

        depositAction.setFont(new java.awt.Font("Barlow", 0, 24)); // NOI18N
        depositAction.setText("Deposit");

        payAction.setFont(new java.awt.Font("Barlow", 0, 24)); // NOI18N
        payAction.setText("Pay");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(payCard, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(payAction)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(depositAction))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(depositCard, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(userPrompt)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(userPrompt)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(depositCard, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payCard, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositAction)
                    .addComponent(payAction))
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel depositAction;
    private component.Card depositCard;
    private javax.swing.JLabel payAction;
    private component.Card payCard;
    private javax.swing.JLabel userPrompt;
    // End of variables declaration//GEN-END:variables

